// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: micro-extrator.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExtractorService_ExtractData_FullMethodName = "/proto.ExtractorService/ExtractData"
)

// ExtractorServiceClient is the client API for ExtractorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExtractorServiceClient interface {
	ExtractData(ctx context.Context, in *ExtractRequest, opts ...grpc.CallOption) (*ExtractResponse, error)
}

type extractorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExtractorServiceClient(cc grpc.ClientConnInterface) ExtractorServiceClient {
	return &extractorServiceClient{cc}
}

func (c *extractorServiceClient) ExtractData(ctx context.Context, in *ExtractRequest, opts ...grpc.CallOption) (*ExtractResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtractResponse)
	err := c.cc.Invoke(ctx, ExtractorService_ExtractData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExtractorServiceServer is the server API for ExtractorService service.
// All implementations must embed UnimplementedExtractorServiceServer
// for forward compatibility.
type ExtractorServiceServer interface {
	ExtractData(context.Context, *ExtractRequest) (*ExtractResponse, error)
	mustEmbedUnimplementedExtractorServiceServer()
}

// UnimplementedExtractorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExtractorServiceServer struct{}

func (UnimplementedExtractorServiceServer) ExtractData(context.Context, *ExtractRequest) (*ExtractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExtractData not implemented")
}
func (UnimplementedExtractorServiceServer) mustEmbedUnimplementedExtractorServiceServer() {}
func (UnimplementedExtractorServiceServer) testEmbeddedByValue()                          {}

// UnsafeExtractorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExtractorServiceServer will
// result in compilation errors.
type UnsafeExtractorServiceServer interface {
	mustEmbedUnimplementedExtractorServiceServer()
}

func RegisterExtractorServiceServer(s grpc.ServiceRegistrar, srv ExtractorServiceServer) {
	// If the following call pancis, it indicates UnimplementedExtractorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExtractorService_ServiceDesc, srv)
}

func _ExtractorService_ExtractData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtractorServiceServer).ExtractData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtractorService_ExtractData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtractorServiceServer).ExtractData(ctx, req.(*ExtractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExtractorService_ServiceDesc is the grpc.ServiceDesc for ExtractorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExtractorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ExtractorService",
	HandlerType: (*ExtractorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExtractData",
			Handler:    _ExtractorService_ExtractData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "micro-extrator.proto",
}
